# Pega esto en Settings → Secrets de tu app en Streamlit Cloud (no lo subas al repo)
[public]
# ID del Google Sheet y nombre de la pestaña (worksheet)
sheet_id = "TU_SHEET_ID"
worksheet = "Hoja 1"

# Método de lectura (no requiere credenciales): usa la vista pública del sheet.
# Asegúrate de que el Sheet esté compartido como "Cualquiera con el enlace: Lector".
# Si el nombre de la pestaña tiene espacios, respétalos tal cual.
# No modifiques esto:
csv_url = "https://docs.google.com/spreadsheets/d/TU_SHEET_ID/gviz/tq?tqx=out:csv&sheet=Hoja 1"

# URL de envío del formulario de Google (termina en /formResponse)
form_action_url = "https://docs.google.com/forms/d/TU_FORM_ID/formResponse"

# Mapeo de columnas -> entry IDs del formulario (en JSON).
# Edita con los entry.<número> de tu formulario (Ver código fuente del formulario para obtenerlos).
entry_map_json = """{
  "Nombre": "entry.111111",
  "Documento": "entry.111112",
  "Link": "entry.111113",
  "Autoridad emisora": "entry.111114",
  "Tipo de documento": "entry.111115",
  "Ámbito de aplicación": "entry.111116",
  "Tema ESG": "entry.111117",
  "Temática ESG": "entry.111118",
  "Descripción": "entry.111119",
  "Aplicación": "entry.111120",
  "Fecha de publicación": "entry.111121",
  "Fecha de aplicación": "entry.111122",
  "Comentarios": "entry.111123",
  "UG 01, 02, 03 - bancos": "entry.111124",
  "UG04 - Asset management": "entry.111125",
  "UG05 - Seguros": "entry.111126",
  "UG06 - LATAM": "entry.111127",
  "UG07 - Corporates": "entry.111128",
  "Estado": "entry.111129",
  "Mes publicación": "entry.111130",
  "Año publicación": "entry.111131"
}"""
